= Nidhogg: Installationsdokumentation
Ives Schneider <ives.schneider@i-401.xyz>
:doctype: pdf
:author: Ives Schneider
:subtitle: Installationsdokumentation
:ntitle: Nidhogg: {subtitle}
:imagesdir: ./images
:class: ITSE17a
:pdf-stylesdir: ./resources/themes
:pdf-fontsdir: ./resources/fonts
:pdf-style: tbz
:allow-uri-read:
:sectnums:
:toc:
:toc-title: Index
:title-page:

== Info
If you're planning to run nidhogg with it's scanning capability, you won't get around to sadly run it as root. (or with cap rights) +
This is due the nmap scanning parameter and arp scanning mechanism. +
Ideally you're using the already created docker, to mitigate some of the security concerns, not all though.

== Requirements
.Linux
- libpcap0.8
- nmap
- curl
- sqlite3-0

WARNING: If you're running Ubuntu chances are high that you'll need to create a symlink for libpcap +
``ln -s /usr/lib/x86_64-linux-gnu/libpcap.so.1.9.1 /usr/lib/x86_64-linux-gnu/libpcap.so.1``

.Windows

== Installation
.From source
1. Clone repository or download source
2. Build nidhogg ``cargo build --release``
3. Manually create config files (see example config.yml)
4. Copy service file to  /etc/systemd/system
5. Activate Unit ``systemctl enable nidhogg``

.Binary (Ubuntu)
1. Download latest .deb
2. Install with dpkg ``dpkg -i xx.deb``
3. Configure application (/etc/nidhogg/)
4. Enable unit ``systemd enable nidhogg``

.Binary (Windows)
Get the Docker image from: +
https://hub.docker.com/r/b401/nidhogg

.Docker
https://hub.docker.com/r/b401/nidhogg
```
docker run -it --net=host --privileged -v config.yml:/etc/nidhogg/config.yml -v mappings.xml:/etc/nidhogg/mappings.xml -v portspecs.yml:/etc/nidhogg/portspecs.yml b401/nidhogg:final
```


== Configuration
WARNING: All configflags are mandatory

See examples for more indepth settings.

=== Main configuration file
Defines most configuration aspects of nidhogg. +
All config flags are mandatory but every functionality can be disabled.

.config.yml
[source,yaml]
----
include::src/config.yml[]
----

=== Portscan configuration files
Defines which target and which ports should be in a special state. +
If a port is undefined, it will be ignored in the final report. +

mappings.xml is used to bind a spec to a target.

Special thanks to https://github.com/lukaspustina/nmap-analyze[nmap-analyze]

.portspecs.yml
[source,yaml]
----
include::src/portspecs.yml[]
----

.mappings.xml
[source,yaml]
----
include::src/mappings.xml[]
----

== Uninstall
Uninstalling is as easy as installing. +
If you've installed nidhogg via .deb, just remove the deb with apt. +

.Ubuntu / apt based
``apt remove nidhogg``

.Compiled from source / Binary
``rm -r /etc/nidhogg && rm /usr/bin/nidhogg``
