# Choose on which address and port the webserver should listen
webserver:
    enable: true
    username: "admin"
    password: "admin"
    address: "0.0.0.0"
    port: "8080"

# Enable or disable mail notifications
mail:
    enable: true
    server: "smtp.gmail.com"
    username: "user@gmail.com"
    password: ""
    email: "user@i-401.xyz"
    from: "user@gmail.com"

# Set address and login to remote Splunk endpoint (multiple endpoints are possible)
splunk:
    enable: true
    server: "splunk:8089"
    username: ""
    password: ""
    interval: 500

# Set remote snmp server address and community + oids.
# Multiple oids and servers are possible
snmp:
    enable: true
    server: "127.0.0.1"
    community: "my_comm"
    oid: "1.3.6.100.1.2.3.5.1.1.0"

# Enable/disable portscanning (requires root rights)
portscan:
    enable: true
    portspec: "/etc/nidhogg/portspecs.yml"
    mappings: "/etc/nidhogg/mappings.xml"
    timeout: 500

# Enable/disable arpscanning (requires root rights)
# Use mac list to whitelist devices. (You won't get notifications if those devices getting connected)
arpscan:
    enable: true
    interface: "eth0"
    db: "/etc/nidhogg/arp.db"
    timeout: 500
    mac:
      - "00:17:88:28:9f:ca"
      - "00:55:da:50:40:64"
      - "34:7e:5c:31:10:e8"
      - "c8:3c:85:3e:e8:dd"
      - "f4:4d:30:68:9b:d4"
